local Test = require("tests.tests")
local lwasm = require("lwasm")

Test:describe("Decoder Tests", function()
	Test:add("decode type section from type.wasm", function()
		local mod = lwasm("build/type.wasm")
		Test:assert_true(mod ~= nil)
		Test:assert_equals(mod.version, 1)
		local type_sec = mod:get_section("type_section")
		Test:assert_true(type_sec ~= nil)
		Test:assert_true(#type_sec.types > 0)
	end)

	Test:add("decode memory section from memory.wasm", function()
		local mod = lwasm("build/memory.wasm")
		Test:assert_true(mod ~= nil)
		local mem_sec = mod:get_section("mem_section")
		Test:assert_true(mem_sec ~= nil)
		Test:assert_true(mem_sec.memory_count > 0)
		Test:assert_true(mem_sec.memory[1].min >= 0)
	end)

	Test:add("decode element section from element.wasm", function()
		local mod = lwasm("build/element.wasm")
		Test:assert_true(mod ~= nil)
		local elem_sec = mod:get_section("element_section")
		Test:assert_true(elem_sec ~= nil)
		Test:assert_true(#elem_sec.elements > 0)
	end)

	Test:add("decode global section from global.wasm", function()
		local mod = lwasm("build/global.wasm")
		Test:assert_true(mod ~= nil)
		local global_sec = mod:get_section("global_section")
		Test:assert_true(global_sec ~= nil)
		Test:assert_true(global_sec.global_count > 0)
		Test:assert_true(#global_sec.globals > 0)
	end)

	Test:add("decode data section from data.wasm", function()
		local mod = lwasm("build/data.wasm")
		Test:assert_true(mod ~= nil)
		local data_sec = mod:get_section("data_section")
		Test:assert_true(data_sec ~= nil)
		Test:assert_true(data_sec.data_count > 0)
		Test:assert_true(#data_sec.entries > 0)
	end)

	Test:add("decode large real-world sqlite3.wasm module", function()
		local mod = lwasm("build/sqlite3.wasm")
		Test:assert_true(mod ~= nil)
		Test:assert_equals(mod.version, 1)
		local code_sec = mod:get_section("code_section")
		Test:assert_true(code_sec ~= nil)
		Test:assert_equals(#code_sec.code, 2668)
		Test:assert_equals(type(code_sec.code[1].body), "string")
		local exp = mod:get_exports()
		Test:assert_true(exp ~= nil)
		Test:assert_true(exp["sqlite3_initialize"] ~= nil)
		Test:assert_true(exp["malloc"] ~= nil)
		Test:assert_true(exp["free"] ~= nil)
	end)
end)

Test:run()
